import type { LevelConfig } from './types';

export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    name: 'Warmup Range',
    bottleCount: 5,
    ammo: 20,
    timeLimit: 60,
    magazineSize: 12,
    movingTargets: false,
    spinningTargets: false,
    heavyCount: 0,
    bonusCount: 0,
    goldCount: 0,
    bottleScale: 1,
    moveSpeed: 0,
    elevatedTargets: false,
    obstacles: false,
    scoreTarget: 400,
  },
  {
    id: 2,
    name: 'Steady Hands',
    bottleCount: 8,
    ammo: 18,
    timeLimit: 55,
    magazineSize: 12,
    movingTargets: false,
    spinningTargets: false,
    heavyCount: 1,
    bonusCount: 1,
    goldCount: 0,
    bottleScale: 0.96,
    moveSpeed: 0,
    elevatedTargets: true,
    obstacles: false,
    scoreTarget: 700,
  },
  {
    id: 3,
    name: 'Moving Glass',
    bottleCount: 10,
    ammo: 16,
    timeLimit: 50,
    magazineSize: 12,
    movingTargets: true,
    spinningTargets: false,
    heavyCount: 1,
    bonusCount: 1,
    goldCount: 0,
    bottleScale: 0.92,
    moveSpeed: 0.9,
    elevatedTargets: true,
    obstacles: false,
    scoreTarget: 1100,
  },
  {
    id: 4,
    name: 'High Shelves',
    bottleCount: 12,
    ammo: 16,
    timeLimit: 48,
    magazineSize: 10,
    movingTargets: true,
    spinningTargets: true,
    heavyCount: 2,
    bonusCount: 1,
    goldCount: 0,
    bottleScale: 0.88,
    moveSpeed: 1.15,
    elevatedTargets: true,
    obstacles: true,
    scoreTarget: 1500,
  },
  {
    id: 5,
    name: 'Tight Ammo',
    bottleCount: 12,
    ammo: 14,
    timeLimit: 44,
    magazineSize: 10,
    movingTargets: true,
    spinningTargets: true,
    heavyCount: 2,
    bonusCount: 2,
    goldCount: 1,
    bottleScale: 0.84,
    moveSpeed: 1.35,
    elevatedTargets: true,
    obstacles: true,
    scoreTarget: 2000,
  },
  {
    id: 6,
    name: 'Spin Line',
    bottleCount: 14,
    ammo: 14,
    timeLimit: 42,
    magazineSize: 8,
    movingTargets: true,
    spinningTargets: true,
    heavyCount: 3,
    bonusCount: 2,
    goldCount: 1,
    bottleScale: 0.8,
    moveSpeed: 1.55,
    elevatedTargets: true,
    obstacles: true,
    scoreTarget: 2600,
  },
  {
    id: 7,
    name: 'Crowded Range',
    bottleCount: 14,
    ammo: 13,
    timeLimit: 40,
    magazineSize: 8,
    movingTargets: true,
    spinningTargets: true,
    heavyCount: 3,
    bonusCount: 2,
    goldCount: 1,
    bottleScale: 0.76,
    moveSpeed: 1.75,
    elevatedTargets: true,
    obstacles: true,
    scoreTarget: 3200,
  },
  {
    id: 8,
    name: 'Marksman Trial',
    bottleCount: 16,
    ammo: 12,
    timeLimit: 38,
    magazineSize: 8,
    movingTargets: true,
    spinningTargets: true,
    heavyCount: 4,
    bonusCount: 2,
    goldCount: 1,
    bottleScale: 0.72,
    moveSpeed: 1.95,
    elevatedTargets: true,
    obstacles: true,
    scoreTarget: 4000,
  },
];

export const TOTAL_LEVELS = LEVELS.length;

export function getLevel(id: number): LevelConfig {
  return LEVELS[Math.max(0, Math.min(LEVELS.length, id) - 1)] ?? LEVELS[0];
}
