export const SOCKET_EVENTS = {
  CHAT: {
    SEND_MESSAGE: 'chat:sendMessage',
    TYPING: 'chat:typing',
    STOP_TYPING: 'chat:stopTyping',
    JOIN_ROOM: 'chat:joinRoom',
    LEAVE_ROOM: 'chat:leaveRoom',
    NEW_MESSAGE: 'chat:newMessage',
    USER_TYPING: 'chat:userTyping',
    USER_STOP_TYPING: 'chat:userStopTyping',
  },

  GAME: {
    CREATE_ROOM: 'game:createRoom',
    JOIN_ROOM: 'game:joinRoom',
    LEAVE_ROOM: 'game:leaveRoom',
    READY: 'game:ready',
    MAKE_MOVE: 'game:makeMove',
    SURRENDER: 'game:surrender',
    OFFER_DRAW: 'game:offerDraw',
    ACCEPT_DRAW: 'game:acceptDraw',
    SPECTATE: 'game:spectate',
    MATCHMAKING: 'game:matchmaking',
    CANCEL_MATCHMAKING: 'game:cancelMatchmaking',
    FILL_BOT: 'game:fillBot',
    ROOM_CREATED: 'game:roomCreated',
    MATCH_FOUND: 'game:matchFound',
    PLAYER_JOINED: 'game:playerJoined',
    PLAYER_LEFT: 'game:playerLeft',
    GAME_START: 'game:gameStart',
    MOVE_MADE: 'game:moveMade',
    GAME_OVER: 'game:gameOver',
    DRAW_OFFERED: 'game:drawOffered',
    SPECTATOR_JOINED: 'game:spectatorJoined',
    COUNTDOWN: 'game:countdown',
    RECONNECTED: 'game:reconnected',
    JOIN: 'game:join',
    LEAVE: 'game:leave',
    STATE: 'game:state',
    SPIN: 'game:spin',
    SPIN_RESULT: 'game:spin:result',
    BALANCE: 'game:balance',
    HISTORY: 'game:history',
    ERROR: 'game:error',
    CREATE: 'game:create',
    ACTION: 'game:action',
    RECONNECT: 'game:reconnect',
    START: 'game:start',
    FINISH: 'game:finish',
    PAUSE: 'game:pause',
    RESUME: 'game:resume',
    CREATED: 'game:created',
    STARTED: 'game:started',
    FINISHED: 'game:finished',
    PLAYER_JOINED_ALIAS: 'game:player_joined',
    PLAYER_LEFT_ALIAS: 'game:player_left',
    SCORE: 'game:score',
  },

  POKER: {
    LOBBY: 'poker:lobby',
    TABLE_CREATE: 'poker:table:create',
    TABLE_JOIN: 'poker:table:join',
    TABLE_LEAVE: 'poker:table:leave',
    TABLE_STATE: 'poker:table:state',
    PLAYER_JOINED: 'poker:player:joined',
    PLAYER_LEFT: 'poker:player:left',
    HAND_START: 'poker:hand:start',
    CARDS_DEALT: 'poker:cards:dealt',
    COMMUNITY_UPDATE: 'poker:community:update',
    ACTION: 'poker:action',
    ACTION_ACCEPTED: 'poker:action:accepted',
    ACTION_REJECTED: 'poker:action:rejected',
    TURN: 'poker:turn',
    DRAW: 'poker:draw',
    DRAW_COMPLETE: 'poker:draw:complete',
    SHOWDOWN: 'poker:showdown',
    HAND_RESULT: 'poker:hand:result',
    POT_UPDATE: 'poker:pot:update',
    BALANCE_UPDATE: 'poker:balance:update',
    TIMER: 'poker:timer',
    ERROR: 'poker:error',
    RECONNECT: 'poker:reconnect',
  },

  NOTIFICATION: {
    SUBSCRIBE: 'notification:subscribe',
    NEW: 'notification:new',
    UNREAD_COUNT: 'notification:unreadCount',
    FRIEND_REQUEST: 'notification:friendRequest',
  },

  PLATFORM: {
    SUBSCRIBE: 'platform:subscribe',
    STATUS: 'platform:status',
  },

  PRESENCE: {
    USER_ONLINE: 'presence:userOnline',
    USER_OFFLINE: 'presence:userOffline',
    ONLINE_USERS: 'presence:onlineUsers',
  },
} as const;
